# it is not really python, but there is no R support on Travis CI yet
language: python

# environment variables
env:
  - R_LIBS_USER=~/R

virtualenv:
  system_site_packages: true

# install dependencies
install:
  - sudo apt-add-repository -y 'deb http://cran.rstudio.com/bin/linux/ubuntu precise/'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install python-numpy python-scipy python-argparse 
  - sudo apt-get install r-base-dev
  - "[ ! -d ~/R ] && mkdir ~/R"
  - ./configure 

# run tests
script:
  - nosetests 
  - "find sandbox/ -name 'default.log' | xargs tail --"
